# Generated by Django 5.1.5 on 2025-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
    ]
