# Generated by Django 5.1.5 on 2025-01-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_entrega_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='aula.tarea'),
        ),
    ]
